### ISSUE TITLE
Change Cloudinary storage for local storage

### ISSUE THREAD

**Issue by Spooder9** [febriadj/messaging-app#1]
Thank you for this great contribution, I would like to know how I can easily change the storage of the sent files and profile images in my local storage on the server that I have for the production of an app based on this tool.

**Comment by febriadj** [comment]
Thank you for opening this issue. I am prepared to assist you, but I need more explanation on this issue.

**Comment by Spooder9** [comment]
Thanks for helping me, basically and to put you in context, I am trying not to use the cloudinary service and use local storage on my server.

I have modified the file server/socket/events/chat.js

![image](https://github.com/febriadj/messaging-app/assets/63208071/8973ab12-0496-4518-b480-8f200068536e)


The file is already saved and displayed when sending, but if I reload the chat or change contacts, the files sent in the chat disappear.

I haven't found a way to prevent them from disappearing.

[https://youtu.be/pGu8NffxxbU](url)

**Comment by febriadj** [comment]
Sure, if you want to store files persistently in the
"/client/public/assets/chat" directory, ensure that your server supports
this feature (persistent storage). Have you tried it on localhost (dev)?

I recommend storing persistent files using object storage such as AWS S3,
Cloudflare R2, or Minio.

**Comment by febriadj** [comment]
Should there be no response, I will close this issue, please reopen if necessary.
