### ISSUE TITLE
How to enable SSL

### ISSUE THREAD

**Issue by tarjomeh** [febriadj/messaging-app#1]
Hi. I could run the app but in Firefox and Chrome most of the UI features do not work like Setting > dark mode. File attachment, voice and call do not work. Any suggestion?

**Comment by febriadj** [comment]
Hello @tarjomeh,

Thanks for opening this issue, I really appreciate your curiosity.

FYI this project is not finished yet, I have never made features like file attachments, voice & video calls. But, the dark mode feature has been completed, but I haven't connected this feature to the **Settings > Dark mode button**.

See [client/redux/reducers/reducer.js](https://github.com/febriadj/messaging-app/blob/master/client/redux/reducers/reducer.js)
![ss](https://user-images.githubusercontent.com/73212374/195303416-b9d048b2-f6c8-423f-ba9e-56556b629ad8.png)

**Comment by tarjomeh** [comment]
Hi again. I could actually enable SSL very easily. However, I get the following error in the browser:

WebSocket connection to 'ws://localhost:8000/socket.io/?EIO=4&transport=websocket' failed:

**Comment by febriadj** [comment]
Maybe it's an error message when the client fails to connect to the server socket, in fact this project is still not stable, I also plan to remodel it someday

**Comment by tarjomeh** [comment]
Ok thank you. I try to debug.
